### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
BREAKING CHANGE: Drop Node 8 support, because [it's EOL](https://nodejs.org/en/about/releases).

### CODE REVIEW

**Comment by kentcdodds** [comment]
I'm not sure why the build is not working. Do you want to try and investigate?

**Comment by MichaelDeBoey** [comment]
I've seen this when updating `jest-dom` too.
Updating the minimum Node version to `10.14` instead of `10.13` solves this.

**Comment by kentcdodds** [comment]
Interesting! Thanks 😁

**Comment by kentcdodds** [comment]
@all-contributors please add @MichaelDeBoey for code

**Pull request merged**
