### PR TITLE
Support quoting scripts to run multiple scripts with the same process.env

### PR DESCRIPTION
**Pull request by kentcdodds**
This passes all the tests, but I don't think that we should do this. `cross-spawn` does a LOT more than `spawn-command`. The only problem is that `cross-spawn` requires that the args are an array  which would require parsing out the command. Unless there's a way to forward the whole string to a command and have that be evaluated... I think `eval` may work on unix, but what about windows?

Help needed!

### CODE REVIEW

**Comment by DanReyLop** [comment]
`crossSpawn('cmd.exe', ['/s', '/c', theWholeCommand])`

That should do the trick, it's basically what `spawn-command` does. Parsing the command is too big a complication to be worth it IMHO.

**Comment by kentcdodds** [comment]
Thanks for chiming in @DanReyLop. Hmmm... Not certain I follow though. Could you make a PR?

**Comment by DanReyLop** [comment]
I've hacked something together [here](https://github.com/kentcdodds/cross-env/commit/89061a3284391699bb3b5d12499a865acc9053db). Obviously it's not production-ready, but it should illustrate my point. The idea is to wrap everything into a shell, so for example:
`cross-env A=asdfg "ls . && ls ."`
Output (Win): `sh -c "ls . && ls ."`
Output (Unix): `cmd.exe /c "ls . && ls ."`

Using `eval` (or `CALL` in Windows) doesn't work because it's a built-in shell command, not an executable command. Invoking a new shell is the closest thing available.

**Comment by DanReyLop** [comment]
Looking at `cross-spawn` I've realized there's a way easier solution, using `spawn("the whole command", [], { shell: true })`, but that was introduced in Node `4.8`, so if you want to raise the minimum version required to run `cross-env`, it's up to you :)

**Comment by kentcdodds** [comment]
Sweet! I think that I'm good with raising the minimum requirement to 4.8. Most people should be there (or will be soon) anyway. Besides, the old cross-env works just fine :)

**Comment by hgwood** [comment]
#89 replaces this PR.

**Pull request closed without merging**
