### PR TITLE
Run tests against same node versions

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by kentcdodds** [comment]
Thanks for doing this! Unfortunately there's some fancy things we'd need to do for our after_success scripts to only run for once of the versions of node we're running. I think we'd be safe to only support v6 though...

**Comment by amilajack** [comment]
Got it. So remove node 4?

**Comment by kentcdodds** [comment]
Yep!

**Comment by amilajack** [comment]
Fixed

**Comment by kentcdodds** [comment]
Thank you!

**Pull request merged**
