### PR TITLE
add appveyor

### LINKED ISSUE #74: do you have/want windows CI?

### PR DESCRIPTION
**Pull request by kellyselden**
This is my first time messing with yarn on appveyor. If you are unfamiliar with appveyor, it's nearly identical to travis. Go there, authenticate with github, then add this project, and then it will pick up this file and test the build.

Resolves #74.

### CODE REVIEW

**Comment by kentcdodds** [comment]
I've enabled appveyor, but it's not building this PR. Do you know what I need to do?

**Comment by kellyselden** [comment]
I rewrote the commit, now appveyor is running.

**Comment by kellyselden** [comment]
I had a feeling it wouldn't pass first try. I'll keep messing with it.

**Comment by kellyselden** [comment]
OK. Good to merge now.

**Pull request merged**
