### PR TITLE
use cross-spawn for spawn compatibility

### LINKED ISSUE #2: spawn ENOENT error [and possible fix?]
Running windows 7, node 4.2.2 x64 bit, npm 2.14.7.

I get the following error when using cross-env:

cross-env-error

After a bunch of digging around, I found that if I replace the usage of ```spawn``` in cross-env with cross-spawn (https://www.npmjs.com/package/cross-spawn) the issue goes away for me.

I can put in a PR if you think adding this dependency is alright.

### PR DESCRIPTION
**Pull request by NogsMPLS**
should fix #2

### CODE REVIEW

**Comment by kentcdodds** [comment]
Thank you! This should be [automatically released](https://egghead.io/lessons/javascript-how-to-write-a-javascript-library-automatically-releasing-with-travisci?series=how-to-write-an-open-source-javascript-library) in a few minutes.

**Comment by kentcdodds** [comment]
Oh... Heh, whoops. My bad, I forgot to ask you to fix the commit message to follow [our standards](https://egghead.io/lessons/javascript-how-to-write-a-javascript-library-writing-conventional-commits-with-commitizen?series=how-to-write-an-open-source-javascript-library)... This wont be auto-released :-(

I'll get it released soon.

**Comment by kentcdodds** [comment]
So I rewrote history and force pushed to master :see_no_evil: 

Your changes have been released. I also just pushed another update that should be released in a moment. If you could let me know whether this actually fixes your windows issues that'd be awesome :D

**Comment by NogsMPLS** [comment]
Apologies on the commit message. Checking out compatibility now, I'll let you know soon.

**Comment by NogsMPLS** [comment]
well, i've tested this with 5 different npm script commands in two different repos now and it fixes 4 of them. I no longer get the ENOENT error at all.

I am having 1 issue however with a specific command that is giving me the following error:

appdata-error

Very frustrating, but still, fixes more things than it doesn't. I'm going to dig further into this appdata issue and see if it's something that can be fixed. (most likely will be a cross-spawn PR, i think.)

**Comment by kentcdodds** [comment]
Cool! Thanks for looking into this @NogsMPLS!

**Pull request merged**
