### PR TITLE
chore: rm yarn.lock, add lock files to .gitignore

### PR DESCRIPTION
**Pull request by sudo-suhas**
The package dependency version for `babel-cli` are out of sync in `package.json`(`6.24.1`) and
`yarn.lock`(`6.23.0`). This adds changes made to the lockfile by yarn after clean install

### CODE REVIEW

**Comment by kentcdodds** [comment]
Hi! Actually, I'd like to remove yarn.lock and add it to the gitignore. Let's add package-lock.json to the gitignore too. It's just not worth the effort for a library.

Could you do that? Thanks!

**Comment by sudo-suhas** [comment]
@kentcdodds No problem. Would you prefer I make a different PR?

**Comment by kentcdodds** [comment]
Either way. You can update this PR too.

**Comment by kentcdodds** [comment]
Ah, we should change the Travis config to use npm instead of yarn. Could you do that too? Thanks!

**Comment by sudo-suhas** [comment]
Happy to help 😄

**Pull request merged**
