### PR TITLE
Feature: Allow specifying default values that are only used if the variable is not set already

### PR DESCRIPTION
**Pull request by iki**
**What**:

Optionally, you can set the variable only if it's not set in environment already:

```json
    "build": "cross-env NODE_ENV?=production webpack --config build/webpack.config.js"
```

That way, the build will default to production environment, but allow you to override it.

**Why**:

We need to provide default NODE_ENV for package.json script command, but allow user to override it.

**How**:

Very simple extension of how the env setter regex match is used.

**Checklist**:
- [x] Documentation
- [x] Tests
- [x] Ready to be merged 
- [x] Added myself to contributors table 

Please check that the contributor is added ok in the first commit, because I had to add it with different method (see #168) and could not run the precommit hook (see #169).

### CODE REVIEW

**Comment by iki** [comment]
Until merge and new release, anyone can try/use the default values by installing `cross-env@iki/cross-env#dist/default-value`.

**Comment by kentcdodds** [comment]
See #157 for why this feature doesn't currently exist and an alternative package you can get if you want this feature. I don't think that I'm going to implement this feature. There are other solutions and I want to avoid complicating this package any further. Thanks though!

**Comment by iki** [comment]
@kentcdodds Ok, will create a new package and link it in other solutions if you prefer that. That said, it's quite common need to let user override the settings from environment, and the change to support this is very small both here and in @naholyr's #157. Actually, I like #157 a lot, but will keep `?=` syntax in the new package because it's simpler for our need.

Maybe some of the 99% of users are not using this feature, because they just didn't see how to do that out of the box ;) Thanks for your work anyway!

**Comment by kentcdodds** [comment]
Hey @iki, cross-env is mostly interested in allowing you to set environment variables in scripts like you do in linux. So if I were to add this feature, it would be implemented in the same way you do it on linux (which I believe is what #157 was intended to do)... If your package starts getting some traction, then I'd take that as evidence of what you say and would be willing to support it in cross-env :)

Thanks!

**Comment by naholyr** [comment]
Agreed for the syntax, I myself used ":=" initially, but then as packaging
it for a PR I thought it had to respect the standards compatibility ;)

**Pull request closed without merging**
