### PR TITLE
remove is-windows dependency

### PR DESCRIPTION
**Pull request by bibo5088**
**What**: Removed "is-windows" from package.json and replace it by a one-liner function

**Why**: The actual function of is-windows is very and short and simple, it contains only one line (https://github.com/jonschlinkert/is-windows/blob/master/index.js#L25).

When downloading is-windows from npm, npm/yarn also downloads the LISCENCE and package.json file which are much bigger than the actual wanted code, as such it's much better to directly include the function in the code than to pull in a package.

Also more packages means more risk, here's an article talking about it :  
[I’m harvesting credit card numbers and passwords from your site. Here’s how.](https://medium.com/hackernoon/im-harvesting-credit-card-numbers-and-passwords-from-your-site-here-s-how-9a8cb347c5b5)

An incident has already happened this year with the package event-stream  :
[Malicious code found in npm package event-stream downloaded 8 million times in the past 2.5 months](https://snyk.io/blog/malicious-code-found-in-npm-package-event-stream/)

**How**: removed the dependency from package.json and added the one liner to is-windows.js, modified the tests to make it work with the new file

**Checklist**:

- [ ] Documentation N/A
- [x] Tests
- [x] Ready to be merged 
- [x] Added myself to contributors table 

I had trouble making the tests work, I feel like having is-windows be a function instead of constant not ideal but it's mandatory if the tests want to mock the OS (unless there is a way to mock a constant)

### CODE REVIEW

**Comment by MeLlamoPablo** [comment]
Recently there has been a lot of controversy within the community with these one-liner packages which depend on each other and fill our `node_modules`. I just wanted to thank you both for actively try to fight this situation!

**Comment by bibo5088** [comment]
No problem, it was very easy.
I was working on one of my projects when I opened yarn.lock and discovered that cross-env was depending on is-windows, I forked the project, replaced the depency with a one line function and submitted a PR.

Yesterday I submitted a PR to remove shebang-regex from another package which is an even bigger offender than is-windows (the regex is only 9 bytes while the packages is in total 2 828 bytes, 314 times bigger).
https://github.com/kevva/shebang-command/pull/4

Hopefully with the next [standard library proposal](https://github.com/tc39/proposal-javascript-standard-library) more and more of these packages will disappear and be replaced by the standard library .

**Comment by MeLlamoPablo** [comment]
Hopefully yes. The big problem is when maintainers disagree with inlining one-liners and actively fight against it (see moxystudio/node-cross-spawn#102).

In that case, the only course of action left is to fork the offending package, inline the dependencies, release it and build trust, and then convince the dependants to switch over the fork. Which is simply too much effort, so we're left in the current state.

**Comment by bibo5088** [comment]
Looks like nice-try and semver were removed.
https://github.com/moxystudio/node-cross-spawn/pull/123
https://github.com/moxystudio/node-cross-spawn/pull/125

But the package has not been updated on npm yet.
https://www.npmjs.com/package/cross-spawn

Soon cross-env will depend on two less sub-depency which is a good thing !

**Pull request merged**
